# Generated by Django 2.0.5 on 2018-08-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions_website1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorquery',
            options={'verbose_name': 'VisitorQuery', 'verbose_name_plural': 'VisitorQueries'},
        ),
        migrations.AddField(
            model_name='visitorquery',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitorquery',
            name='processed',
            field=models.DateTimeField(null=True),
        ),
    ]
