# Generated by Django 2.0.5 on 2018-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions_website1', '0002_auto_20180829_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha2',
            field=models.CharField(db_index=True, default='  ', max_length=2, unique=True, verbose_name='Alpha-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='intermregion',
            field=models.CharField(db_index=True, max_length=80, null=True, verbose_name='Intermediate Region'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(db_index=True, max_length=80, null=True, verbose_name='Sub Region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Country Code'),
        ),
    ]
