# Generated by Django 2.1 on 2018-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions_website1', '0003_auto_20180829_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorquery',
            name='complete_region',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
