# Generated by Django 2.1 on 2018-09-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotions_website1', '0004_visitorquery_complete_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.IntegerField(verbose_name='Index')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions_website1.VisitorQuery')),
            ],
            options={
                'verbose_name': 'Visitor Query Result',
                'verbose_name_plural': 'Visitor Query Results',
            },
        ),
        migrations.CreateModel(
            name='VisitorResultEmotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angry', models.FloatField()),
                ('disgusted', models.FloatField()),
                ('fearful', models.FloatField()),
                ('happy', models.FloatField()),
                ('sad', models.FloatField()),
                ('surprised', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
            options={
                'verbose_name': 'Visitor Result Emotion',
                'verbose_name_plural': 'Visitor Result Emotions',
            },
        ),
    ]
