# Generated by Django 2.1 on 2018-09-05 14:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emotions_website1', '0005_visitorqueryresult_visitorresultemotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorqueryresult',
            name='emotions',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Emotions'),
        ),
        migrations.AddField(
            model_name='visitorqueryresult',
            name='original_path',
            field=models.CharField(max_length=255, null=True, verbose_name='Original'),
        ),
        migrations.AlterField(
            model_name='visitorqueryresult',
            name='image_path',
            field=models.CharField(max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='visitorqueryresult',
            name='index',
            field=models.IntegerField(null=True, verbose_name='Index'),
        ),
    ]
